export const DISCOVER_REQUEST = "DISCOVER_REQUEST"
export const DISCOVER_SUCCESS = "DISCOVER_SUCCESS"
export const DISCOVER_FAIL = "DISCOVER_FAIL"

export const POPULAR_REQUEST = "POPULAR_REQUEST"
export const POPULAR_SUCCESS = "POPULAR_SUCCESS"
export const POPULAR_FAIL = "POPULAR_FAIL"

export const FAVORITES_REQUEST = "FAVORITE_REQUEST"
export const FAVORITES_SUCCESS = "FAVORITE_SUCCESS"
export const FAVORITES_FAIL = "FAVORITE_FAIL"

export const ADD_FAVORITES_REQUEST = "ADD_FAVORITE_REQUEST"
export const ADD_FAVORITES_SUCCESS = "ADD_FAVORITE_SUCCESS"
export const ADD_FAVORITES_FAIL = "ADD_FAVORITE_FAIL"

export const REMOVE_FAVORITES_REQUEST = "REMOVE_FAVORITE_REQUEST"
export const REMOVE_FAVORITES_SUCCESS = "REMOVE_FAVORITE_SUCCESS"
export const REMOVE_FAVORITES_FAIL = "REMOVE_FAVORITE_FAIL"

export const LATEST_REQUEST = "LATEST_REQUEST"
export const LATEST_SUCCESS = "LATEST_SUCCESS"
export const LATEST_FAIL = "LATEST_FAIL"

export const SEARCH_REQUEST = "SEARCH_REQUEST"
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"
export const SEARCH_FAIL = "SEARCH_FAIL"

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST"
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS"
export const MOVIE_DETAILS_FAIL = "MOVIE_DETAILS_FAIL"


export const CLEAR_ERRORS   =  "CLEAR_ERRORS" 